CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE TABLE "Facilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" text NOT NULL,
        CONSTRAINT "PK_Facilities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE TABLE "Rooms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Capacity" integer NOT NULL,
        "Type" text NOT NULL,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE TABLE "RoomFacilities" (
        "FacilityId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        CONSTRAINT "PK_RoomFacilities" PRIMARY KEY ("RoomId", "FacilityId"),
        CONSTRAINT "FK_RoomFacilities_Facilities_FacilityId" FOREIGN KEY ("FacilityId") REFERENCES "Facilities" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RoomFacilities_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE TABLE "Schedules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "UserId" integer,
        "Type" text NOT NULL,
        "Start" timestamp with time zone NOT NULL,
        "End" timestamp with time zone NOT NULL,
        "Status" text NOT NULL,
        "Description" text,
        "Reason" text,
        CONSTRAINT "PK_Schedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Schedules_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Schedules_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE INDEX "IX_RoomFacilities_FacilityId" ON "RoomFacilities" ("FacilityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE INDEX "IX_Schedules_RoomId" ON "Schedules" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    CREATE INDEX "IX_Schedules_UserId" ON "Schedules" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250115172552_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250115172552_Initial', '9.0.1');
    END IF;
END $EF$;
COMMIT;

